# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_blog', to='blog.article', verbose_name='مقاله')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_blog_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر علاقه مند')),
            ],
            options={
                'verbose_name': 'مقاله\u200cی مورد علاقه',
                'verbose_name_plural': 'مقاله\u200cهای مورد علاقه',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر علاقه مند')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_food', to='food.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'غذای مورد علاقه',
                'verbose_name_plural': 'غذاهای مورد علاقه',
            },
        ),
    ]
