# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(help_text='عنوان تبلیغ را وارد کنید.', max_length=100, verbose_name='عنوان تبلیغ')),
                ('ad_action_model', models.CharField(choices=[('1', 'رنگ'), ('2', 'لرزش'), ('3', 'گردش'), ('4', 'تار')], default='1', help_text='شما می توانید یک انیمیشن را به متن رویداد اضافه کنید.', max_length=100, verbose_name='انیمیشن متن نمایشی')),
                ('ad_url', models.URLField(help_text='لینکی است که با کلیک کردن کاربر بر روی آن کند آن صفحه باز میشود', max_length=255, verbose_name='لینک انتقال صفحه')),
                ('ad_image', models.ImageField(help_text='تصویری است که به کاربر نمایش داده میشود.', upload_to='images/ad/Ad/', verbose_name='بنر بتلیغ')),
                ('ad_start_date', models.DateField(auto_now_add=True, help_text='شما می توانید زمان انتشار را مشخص کنید.', verbose_name='زمان شروع انتشار')),
                ('ad_end_date', models.DateField(help_text='شما می توانید با تنظیم تاریخ پایان انتشار را مشخص کنید.', verbose_name='زمان پایان انتشار')),
                ('ad_is_active', models.BooleanField(default=False, help_text='', verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'db_table': 'table_ads',
            },
        ),
    ]
