# Generated by Django 4.0.5 on 2023-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_is_active',
            field=models.BooleanField(default=False, help_text='', verbose_name='فعال/غیرفعال'),
        ),
    ]
