# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(help_text='نام شعبه را به صورت فارسی وارد کنید.', max_length=180, verbose_name='نام شعبه')),
                ('branch_number', models.IntegerField(help_text='شماره شعبه در کشور خود را وارد کنید.', verbose_name='شماره شعبه')),
                ('branch_capacity', models.IntegerField(verbose_name='ظرفیت شعبه')),
                ('branch_number_of_tables', models.IntegerField(verbose_name='تعداد میزهای شعبه')),
                ('branch_address', models.TextField(verbose_name='آدرس شعبه')),
                ('branch_google_map_link', models.URLField(blank=True, null=True, verbose_name='لیتک گوگل مپ')),
                ('branch_3d_map_link', models.URLField(blank=True, null=True, verbose_name='نقشه سه بعدی شعبه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('branch_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city', verbose_name='شهری که در آن خدمات اراعه می کنید.')),
                ('branch_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country', verbose_name='کشوری که در آن خدمات اراعه می کنید.')),
                ('branch_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدیر شعبه')),
                ('branch_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state', verbose_name='استان یا ایالتی که در آن خدمات اراعه می کنید.')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
                'db_table': 'table_branches',
            },
        ),
    ]
