# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise_time', models.TimeField(verbose_name='تایین زمان ارسال وعده')),
                ('day_of_week', models.CharField(choices=[('1', 'شنبه'), ('2', 'یک\u200cشنبه'), ('3', 'دوشنبه'), ('4', 'سه\u200cشنبه'), ('5', 'چهارشنبه'), ('6', 'پنج\u200cشنبه'), ('7', 'جمعه')], max_length=100, verbose_name='روز هفته')),
                ('description', models.TextField(verbose_name='توضحات')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('foods', models.ManyToManyField(to='food.food', verbose_name='غذاهای وعده')),
                ('my_recipes', models.ManyToManyField(to='food.myrecipes', verbose_name='غذاهای وعده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وعده غذایی کاربر',
                'verbose_name_plural': 'وعده های غذایی کاربر',
                'db_table': 'table_promise',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_title', models.CharField(default='یک ماهه', max_length=50, verbose_name='عنوان اشتراک')),
                ('subscription_price', models.PositiveIntegerField(default=200000, verbose_name='قیمت اشتراک')),
                ('subscription_discount', models.PositiveIntegerField(default=200000, verbose_name='تخفیف به تومان')),
                ('is_special_for_new_users', models.BooleanField(default=True, verbose_name='ویؤه کاربران جدید است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک های کاربر',
                'db_table': 'table_subscription_user',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('promise', models.ManyToManyField(to='subscription.promise', verbose_name='وعده های غذایی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک',
                'verbose_name_plural': 'اشتراک',
                'db_table': 'table_subscription',
            },
        ),
    ]
