# Generated by Django 4.0.5 on 2023-08-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionuser',
            name='subscription',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription', verbose_name='اشتراکی که فعال شده است.'),
            preserve_default=False,
        ),
    ]
