# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='نام')),
                ('family', models.CharField(max_length=15, verbose_name='نام خانوادگی')),
                ('message', models.TextField(verbose_name='پیام')),
                ('email', models.EmailField(max_length=220, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=300, verbose_name='عنوان')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت دیده شده')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان ثبت')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'db_table': 'table_messages',
            },
        ),
        migrations.CreateModel(
            name='UserChatRoom',
            fields=[
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام\u200cخانوادگی')),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='شماره موبایل')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('avatar', models.CharField(choices=[('images/avatar/avatar_1.png', 'آواتار شماره یک'), ('images/avatar/avatar_2.png', 'آواتار شماره دو'), ('images/avatar/avatar_3.png', 'آواتار شماره سه'), ('images/avatar/avatar_4.png', 'آواتار شماره چهار')], default='images/avatar/avatar_1.png', max_length=50, verbose_name='آواتار')),
                ('is_exist', models.BooleanField(default=False, verbose_name='ثبت شده؟')),
                ('is_support', models.BooleanField(default=False, verbose_name='پشتیببان است؟')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'کاربر چت روم',
                'verbose_name_plural': 'کاربران چت روم',
                'db_table': 'table_user_chat_room',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='متن پیام')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_seen', models.BooleanField(default=False, verbose_name='وضعیت دیده شده')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('message_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_child', to='message.chatroom', verbose_name='والد پیام')),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_user', to='message.userchatroom', verbose_name='گیرنده')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to='message.userchatroom', verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'چت روم',
                'verbose_name_plural': 'چت روم',
                'db_table': 'table_chat_room',
            },
        ),
    ]
