# Generated by Django 4.0.5 on 2023-07-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mobile_number',
            field=models.CharField(default='09932062665', help_text='شماره موبایل کاربر جدید را وارد کنید. نکته: شماره تماس کاربر نمی\u200cتواند تکراری باشد.', max_length=11, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=220, null=True, verbose_name='ایمیل'),
        ),
    ]
