# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='سوال پرسیده شده')),
                ('answer', models.TextField(verbose_name='پاسخ چت جی پی تی')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.userchatroom', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'هوش مصنوعی',
                'verbose_name_plural': 'هوش مصنوعی',
                'db_table': 'table_Chat_GPT',
            },
        ),
    ]
