# Generated by Django 4.0.5 on 2023-07-30 01:07

import apps.main.models
import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frequently_asked_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, verbose_name='سوال')),
                ('response', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='پاسخ')),
                ('register_date', models.DateField(auto_now=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'سوال\u200c متداول',
                'verbose_name_plural': 'سوال\u200cهای متداول',
                'db_table': 'table_frequently_asked_question',
            },
        ),
        migrations.CreateModel(
            name='Slid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slid_title', models.CharField(help_text='شما می\u200cتوانید برای اسلایدر عنوان مشخص کنید.', max_length=100, verbose_name='عنوان اسلاید')),
                ('slid_color', colorfield.fields.ColorField(default='#FFF', help_text='شما می\u200cتوانید رنگ عنوان را مشخص کنید.', image_field=None, max_length=18, samples=None, verbose_name='رنگ متن عنوان')),
                ('slid_url', models.URLField(help_text='آدرس صفحه\u200cای که می\u200cخواهید با کلیک کاربر به آن صفحه هدایت شود.', max_length=255, verbose_name='آدرس اسلاید')),
                ('slid_image', models.ImageField(blank=True, help_text='تصویری که برای این اسلاید در نظر دارید را انتخاب کنید. نکته: بهتر است از عکس\u200c با فرمت webp استفاده کنید.', null=True, upload_to='images/main/slider', verbose_name='تصویر اسلاید')),
                ('slid_video', models.FileField(blank=True, help_text='در صورتی که می\u200cخواهید اسلاید متحرک باشد فایل gif(متحرک) خود را بارگذاری کنید. نکته: فرمت فایل باید gif باشد.', null=True, upload_to='videos/main/slider', validators=[apps.main.models.validate_video_extension], verbose_name='اسلاید ویدیویی')),
                ('slid_type', models.CharField(choices=[('1', 'اسلاید ویدئویی'), ('2', 'اسلاید تصویری')], help_text='نوع فایل بارگذاری شده را انتخاب کنید.', max_length=100, verbose_name='نوع اسلاید')),
                ('slid_start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان شروع')),
                ('slid_end_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ و زمان پایان')),
                ('slid_register_date', models.DateTimeField(auto_now_add=True)),
                ('slid_is_active', models.BooleanField(default=False, help_text='شما با فعال و یا غیرقعال کردن این گزینه می توانید وضعبت انتشار را مشخص کنید.', verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'db_table': 'table_slids',
            },
        ),
    ]
