# Generated by Django 4.0.5 on 2023-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customer_image_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude_location',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='عرض جغرافیایی کاربر'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude_location',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='طول جغرافیایی کاربر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude_location',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='عرض جغرافیایی کاربر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude_location',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='طول جغرافیایی کاربر'),
        ),
    ]
