# Generated by Django 4.0.5 on 2023-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customer_latitude_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude_location',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='عرض جغرافیایی کاربر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude_location',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='طول جغرافیایی کاربر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude_location',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='عرض جغرافیایی کاربر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude_location',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='طول جغرافیایی کاربر'),
        ),
    ]
