# Generated by Django 4.0.5 on 2023-07-30 01:07

import apps.mukbang.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mukbang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveBigIntegerField(default=0, verbose_name='تعداد پستندیده\u200cها')),
                ('dislike', models.PositiveBigIntegerField(default=0, verbose_name='تعداد نپستندیده\u200cها')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('share_number', models.PositiveBigIntegerField(default=0, verbose_name='تعداد اشتراک گذاشته شده')),
                ('video', models.FileField(upload_to='videos/Mukbang/videos', validators=[apps.mukbang.models.validate_mukbang_video], verbose_name='ویدئو')),
                ('poster_image', models.ImageField(upload_to='images/Mukbang/poster_image', verbose_name='تصویر پوستر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('register_date', models.DateField(auto_now=True, verbose_name='تاریخ درج')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('food', models.ManyToManyField(to='food.food', verbose_name='غذاها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'موکبانگ',
                'verbose_name_plural': 'موکبانگ\u200cها',
                'db_table': 'table_mukbangs',
            },
        ),
    ]
