# Generated by Django 4.0.5 on 2023-07-30 01:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30, verbose_name='عنوان رویداد')),
                ('event_text', models.TextField(verbose_name='متن رویداد')),
                ('event_action_text', models.CharField(max_length=4, verbose_name='متن نمایشی')),
                ('event_action_model', models.CharField(choices=[('1', 'رنگ'), ('2', 'لرزش'), ('3', 'گردش'), ('4', 'تار')], default='1', help_text='شما می توانید یک انیمیشن را به متن رویداد اضافه کنید.', max_length=100, verbose_name='انیمیشن متن نمایشی')),
                ('event_image', models.ImageField(upload_to='images/event', verbose_name='تصویر رویداد')),
                ('event_register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('event_start_date', models.DateTimeField(verbose_name='تاریخ و زمان شروع رویداد')),
                ('event_end_date', models.DateTimeField(verbose_name='تاریخ و زمان پایان رویداد')),
                ('event_url', models.URLField(verbose_name='آدرس صفحه یا آدرس تارنما')),
                ('event_is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'db_table': 'table_events',
            },
        ),
        migrations.CreateModel(
            name='Footer_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=300, verbose_name='عنوان رویداد')),
                ('event_action_text', models.CharField(max_length=100, verbose_name='متن نمایشی')),
                ('event_action_model', models.CharField(choices=[('1', 'رنگ'), ('2', 'لرزش'), ('3', 'گردش'), ('4', 'تار')], default='1', help_text='شما می توانید یک انیمیشن را به متن رویداد اضافه کنید.', max_length=100, verbose_name='انیمیشن متن نمایشی')),
                ('event_start_date', models.DateTimeField(verbose_name='تاریخ و زمان شروع رویداد')),
                ('event_end_date', models.DateTimeField(verbose_name='تاریخ و زمان پایان رویداد')),
                ('event_url', models.URLField(verbose_name='آدرس صفحه یا آدرس تارنما')),
                ('event_is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'رویداد پایین تارنما',
                'verbose_name_plural': 'رویدادها پایین تارنما',
                'db_table': 'table_footer_events',
            },
        ),
        migrations.CreateModel(
            name='Top_Menu_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=300, verbose_name='عنوان رویداد')),
                ('event_title_color', colorfield.fields.ColorField(default='#FFF', image_field=None, max_length=18, samples=None, verbose_name='رنگ متن')),
                ('event_action_text', models.CharField(max_length=100, verbose_name='متن نمایشی')),
                ('event_action_model', models.CharField(choices=[('1', 'رنگ'), ('2', 'لرزش'), ('3', 'گردش'), ('4', 'تار')], default='1', help_text='شما می توانید یک انیمیشن را به متن رویداد اضافه کنید.', max_length=100, verbose_name='انیمیشن متن نمایشی')),
                ('event_image', models.ImageField(upload_to='images/top_menu_event', verbose_name='تصویر رویداد')),
                ('event_register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('event_start_date', models.DateField(verbose_name='تاریخ و زمان شروع رویداد')),
                ('event_end_date', models.DateField(verbose_name='تاریخ و زمان پایان رویداد')),
                ('event_url', models.URLField(verbose_name='آدرس صفحه یا آدرس تارنما')),
                ('event_is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'رویداد بالای تارنما',
                'verbose_name_plural': 'رویدادها بالای تارنما',
                'db_table': 'table_top_menu_events',
            },
        ),
    ]
