# Generated by Django 4.0.5 on 2023-07-30 01:07

import apps.blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_avatar', models.ImageField(help_text='لطفا غکس خود را بارگذاری کنید. نکته: بهتر است فرمت فایل بارگذاری شده webp باشد تا در سرعت سایت مشکلی پیش نیاید.', upload_to='images/blog/author/', verbose_name='آواتار')),
                ('author_name', models.CharField(help_text='نکته: لطفا نام خود را به زبان فارسی بنویسید.', max_length=60, verbose_name='نام نویسنده')),
                ('author_family', models.CharField(help_text='نکته: لطفا نام خانوادگی خود را به زبان فارسی بنویسید.', max_length=60, verbose_name='نام خانوادگی نویسنده')),
                ('author_fullname', models.CharField(help_text='لطفا در وارد کردن نام و نام خانوادگی خود دقت فرمایید.', max_length=120, verbose_name='نام و نام خانوادگی نویسنده')),
                ('author_slug', models.SlugField(help_text='لطفا در وارد کردن اسلاگ بسیار دقت کنید. نکته: اسلاگ را باید به زبان انگلیسی وارد کنید و برای جدا سازی کلمات از - یا _ استفاده کنید.', max_length=65, verbose_name='اسلاگ')),
                ('author_email', models.EmailField(help_text='لطفا ایمیل را با دقت وارد نمایید.', max_length=250, null=True, verbose_name='ایمیل')),
                ('author_phone', models.CharField(default='+98', help_text='شماره تماس را به درستی وارد کنید. نکته: نیازی به وارد کردن پیش شماره کشور نیست.', max_length=14, null=True, verbose_name='شماره موبایل')),
                ('author_cv', models.FileField(help_text='لطفا رزومه خود را بارگذاری کنید. نکته: فرمت فایل باید docx و یا pdf  باشد.', upload_to='files/author/cv', validators=[apps.blog.models.validate_author_cv], verbose_name='رزومه')),
                ('author_info', models.TextField(help_text='لطفا توضیجی مختصر در مورد خود بنویسید.', verbose_name='توضیحات')),
                ('author_is_active', models.BooleanField(default=False, help_text='شما با قعال و یا غیرفعال کردن این قسمت می توانید فعالیت نویسنده را کنترل کنید.', verbose_name='وضعت فعال / غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'db_table': 'table_authors',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='نکته: در انتخاب کلمه کلیدی بسیار دقت کنید تا از نظر سئو سایت به مشکل بر نخورد.', max_length=120, verbose_name='کلمه')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'کلید\u200cواژه',
                'verbose_name_plural': 'کلیدواژه\u200cها',
                'db_table': 'table_key_words',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(help_text='یکی از مهمترین بخش در سئو انتخاب درست عنوان یک مقاله است، پس به آن توجه کنید. نکته: عنوان مقاله باید دارای مفهوم باشد و با متن مقاله در ارتباط باشد.', max_length=60, verbose_name='عنوان مقاله')),
                ('article_slug', models.SlugField(help_text='لطفا در وارد کردن اسلاگ بسیار دقت کنید. نکته: اسلاگ را باید به زبان انگلیسی وارد کنید و برای جدا سازی کلمات از - یا _ استفاده کنید.', max_length=200)),
                ('article_short_url', models.URLField(blank=True, help_text='این قسمت را می توانید خالی بگذارید زیرا که سیستم خودکار این لینک را تولید می کند.', null=True, verbose_name='لینک کوتاه')),
                ('article_main_image', models.ImageField(help_text='تصویر اصلی مقاله را بارگذاری کنید. این تصویر در نمایش مقالات و بالای مقاله به نمایش در می\u200cآید.', upload_to='images/blog/article', verbose_name='تصویر اصلی مقاله')),
                ('article_summary_text', models.TextField(blank=True, help_text='در این قسمت باید یک خلاصه در مورد این مقاله بنویسید. این متن در قسمت اشتراک گذاری به همراه لینک صفحه ارسال می شود.', null=True, verbose_name='متن خلاصه مقاله')),
                ('article_main_text', ckeditor_uploader.fields.RichTextUploadingField(help_text='در این قسمت محیطی در اختیار شما قرار گرفته است که می\u200cتوانید متن مقاله را تایپ و ادیت کنید همچنین می\u200cتوانید از جداول و ... به مقاله اضافه کنید.', verbose_name='متن اصلی مقاله')),
                ('article_register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت مقاله')),
                ('article_publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار مقاله')),
                ('article_update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین ویرایش مقاله')),
                ('article_read_time', models.IntegerField(help_text='لطفا مقدار زمان برای مطالعه این مقاله را وارد کنید.', verbose_name='مدت زمان مطالعه مقاله')),
                ('article_is_active', models.BooleanField(default=False, help_text='شما می\u200cتوانید با فعال کردن این قسمت مجوز انتشار مقاله را صادر کنید.', verbose_name='وضعت فعال / غیرفعال')),
                ('article_file', models.FileField(blank=True, help_text='در صورتی که این مقاله فایل پی دی اف داشت می توانید آن را بارگذاری کنید تا کاربران بتوانند آن را دانلود کنند.', null=True, upload_to='files/article/pdf', validators=[apps.blog.models.validate_article_PDF_file], verbose_name='فایل پی دی اف مقاله')),
                ('article_visits', models.PositiveSmallIntegerField(default=0, editable=False, help_text='تعداد بازدید به صورت خودکار پر می شود.', verbose_name='تعداد بازدید')),
                ('article_group', models.CharField(help_text='در این قسمت باید گروه مقاله را مشخص کنید. مثال: آموزشی', max_length=200, verbose_name='گروه مقاله')),
                ('article_likes', models.PositiveBigIntegerField(default=0, verbose_name='تعداد پسندیده\u200cها شده')),
                ('article_dislikes', models.PositiveBigIntegerField(default=0, verbose_name='تعداد پسندیده\u200cها نشده')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('article_author', models.ManyToManyField(to='blog.author', verbose_name='نویسنده مقاله')),
                ('article_key_words', models.ManyToManyField(blank=True, help_text='کلمات کلیدی مرتبط به این مقاله را انتخاب کنید. توجه کنید. باید کلمات کلیدی را به درستی انتخاب کنید تا سئو سایت به مشکل بر نخورد.', related_name='article_key_words', to='blog.keyword', verbose_name='کلمات کلیدی مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'db_table': 'table_articles',
            },
        ),
    ]
