# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش پرداخت')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(verbose_name='توضیحات پرداخت')),
                ('is_finally', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت درگاه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='شماره پیگیری پرداخت')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='accounts.customer', verbose_name='مشتری')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.order', verbose_name='سفارش')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=120, verbose_name='واحد پول')),
                ('ISO_code', models.CharField(max_length=5, verbose_name='کد ایزو')),
                ('symbol', models.CharField(max_length=30, verbose_name='علامت اختصاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'واحد پول',
                'verbose_name_plural': 'واحدهای پول',
            },
        ),
    ]
