# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='robot_takes_containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150, verbose_name='مدل ربات')),
                ('google_map_location_link', models.URLField(blank=True, null=True, verbose_name='آدرس گوگل مپ ربات')),
                ('city_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city', verbose_name='شهری که ربات در آن فعاللیت می\u200cکند')),
                ('country_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country', verbose_name='کشوری که ربات در آن فعاللیت می\u200cکند')),
                ('state_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state', verbose_name='استانی که ربات در آن فعاللیت می\u200cکند')),
            ],
            options={
                'verbose_name': 'ربات گیرنده ظروف',
                'verbose_name_plural': 'ربات\u200cهای گیرینده ظروف',
                'db_table': 'table_robot_takes_containers',
            },
        ),
        migrations.CreateModel(
            name='my_environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_dishes', models.PositiveIntegerField(default=0, verbose_name='تعداد ظروفی که کاربر به دستگاه داده است')),
                ('points_unit', models.PositiveIntegerField(default=50, verbose_name='واحد امتیاز')),
                ('robot_takes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_environment.robot_takes_containers', verbose_name='رباتی که ظروف را گرفته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربری که ظروف را به دست گاه تحویل داده است')),
            ],
            options={
                'verbose_name': 'کاربر محیط زیستی',
                'verbose_name_plural': 'کاربران محیط زیستی',
                'db_table': 'table_my_environment',
            },
        ),
    ]
