# Generated by Django 4.0.5 on 2023-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot_takes_containers',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
