# Generated by Django 4.0.5 on 2023-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_environment', '0002_robot_takes_containers_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot_takes_containers',
            name='google_map_location_link',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس گوگل مپ ربات'),
        ),
    ]
