# Generated by Django 4.0.5 on 2023-08-03 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionuser_subscription'),
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='register_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درج'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='how_to_use',
            field=models.CharField(choices=[('1', 'ارسال مواد خام به همراه دستور غذاها'), ('2', 'ارسال غذاها پخته شده'), ('3', 'رزور غذاها')], default='2', max_length=120, verbose_name='چگونگی مصرف'),
        ),
        migrations.CreateModel(
            name='OrderDetailsSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details_subscription', to='orders.order', verbose_name='سفارش')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
            ],
        ),
    ]
