# Generated by Django 4.0.5 on 2023-08-04 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='register_date_time',
        ),
    ]
