# Generated by Django 4.0.5 on 2023-07-30 01:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='عنوان ایمیل')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن ایمیل')),
                ('mod', models.CharField(choices=[('1', 'ارسال به تمامی کاربران'), ('2', 'ارسال به کاربران مشخص شده'), ('3', 'ارسال به کاربران کشور'), ('4', 'ارسال به مدیران'), ('5', 'ارسال به پشتیبانان'), ('6', 'ارسال به خدمات دهنده\u200cها')], max_length=120, verbose_name='حالت ایمیل')),
                ('register_date_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیلها',
                'db_table': 'table_email',
            },
        ),
    ]
