# Generated by Django 4.0.5 on 2023-07-30 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='country',
            field=models.ManyToManyField(to='accounts.country', verbose_name='کشورها'),
        ),
        migrations.AddField(
            model_name='email',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
    ]
