# Generated by Django 4.0.5 on 2023-07-30 01:07

import apps.food.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=60, verbose_name='نام غذا')),
                ('food_slug', models.SlugField(max_length=120)),
                ('food_image', models.ImageField(upload_to='images/food/food', verbose_name='تصویر غذا')),
                ('food_price', models.IntegerField(default=0, verbose_name='قیمت غذا')),
                ('food_time', models.CharField(max_length=3, verbose_name='زمان پخت غذا')),
                ('food_wight', models.CharField(max_length=10, verbose_name='وزن غذا')),
                ('food_calories', models.CharField(max_length=10, verbose_name='کالری غذا')),
                ('food_description', models.TextField(verbose_name='توضیحات غذا')),
                ('food_is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='register date')),
                ('food_sales_number', models.PositiveIntegerField(default=0, verbose_name='تعداد غذای فروخته شده')),
                ('food_views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('profit', models.PositiveIntegerField(verbose_name='سود حاصل از فروش این غذا')),
                ('is_auto_compile_price', models.BooleanField(default=True, verbose_name='به دست آوردن قیمت به صورت خودکار')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'db_table': 'table_food',
            },
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='نام دسته')),
                ('group_image', models.ImageField(upload_to='images/food/food_group/', verbose_name='تصویر گروه')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی غذا',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای غذا',
                'db_table': 'table_food_group',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50, verbose_name='نام وعده غذایی')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'وعده غذایی',
                'verbose_name_plural': 'وعده های غذایی',
                'db_table': 'table_food_meal',
            },
        ),
        migrations.CreateModel(
            name='StuffGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='نام دسته')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مواد',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مواد',
                'db_table': 'table_stuff_group',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=200, verbose_name='نام ماده')),
                ('stuff_price_auto', models.BooleanField(default=True, verbose_name='بروزرسانی قیمت')),
                ('stuff_image', models.CharField(default='images/food/stuffs/none.jpg', max_length=500, verbose_name='آدرس تصویر گروه')),
                ('stuff_price', models.IntegerField(verbose_name='قیمت ماده به تومان')),
                ('stuff_register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ماده')),
                ('stuff_update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین ماده ')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('stuff_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.stuffgroup', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ماده',
                'verbose_name_plural': 'مواد',
                'db_table': 'table_stuff',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_image', models.ImageField(upload_to='images/food/recipes/', verbose_name='تصویر غذا')),
                ('recipe_slug', models.SlugField(max_length=120)),
                ('recipe', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='دستور پخت')),
                ('recipe_name', models.CharField(max_length=60, verbose_name='نام دستور')),
                ('recipe_summary_text', models.TextField(help_text='در این قسمت باید یک خلاصه در مورد این دستور بنویسید. این متن در قسمت اشتراک گذاری به همراه لینک صفحه ارسال می شود.', verbose_name='متن خلاصه دستور غذا')),
                ('recipe_file', models.FileField(blank=True, help_text='در صورتی که این دستور غذا فایل پی دی اف داشت می توانید آن را بارگذاری کنید تا کاربران بتوانند آن را دانلود کنند.', null=True, upload_to='files/recipe/pdf', validators=[apps.food.models.validate_recipes_PDF_file], verbose_name='فایل پی دی اف دستور غذا')),
                ('recipe_short_url', models.URLField(blank=True, help_text='این قسمت را می توانید خالی بگذارید زیرا که سیستم خودکار این لینک را تولید می کند.', null=True, verbose_name='لینک کوتاه')),
                ('recipe_views', models.PositiveIntegerField(verbose_name='بازدیدها')),
                ('recipe_video', models.FileField(blank=True, null=True, upload_to='videos/Recipes/videos', validators=[apps.food.models.validate_recipes_video], verbose_name='ویدئو آمورزشی دستور')),
                ('recipe_likes', models.PositiveBigIntegerField(default=0, verbose_name='تعداد پسندیده\u200cها شده')),
                ('recipe_dislikes', models.PositiveBigIntegerField(default=0, verbose_name='تعداد پسندیده\u200cها نشده')),
                ('recipe_register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت دستور')),
                ('recipe_publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار دستور')),
                ('recipe_update_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آخرین ویرایش دستور')),
                ('recipe_is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('recipe_key_words', models.ManyToManyField(help_text='کلمات کلیدی مرتبط به این دستور غذا را انتخاب کنید. توجه کنید. باید کلمات کلیدی را به درستی انتخاب کنید تا سئو سایت به مشکل بر نخورد.', related_name='recipe_key_words', to='blog.keyword', verbose_name='کلمات کلیدی دستور غذا')),
                ('recipe_stuffs', models.ManyToManyField(to='food.stuff', verbose_name='مواد استفاده شده')),
            ],
            options={
                'verbose_name': 'دستور پخت',
                'verbose_name_plural': 'دستورات پخت',
                'db_table': 'table_food_recipes',
            },
        ),
        migrations.CreateModel(
            name='MyRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes_name', models.CharField(max_length=160, verbose_name='نام دستور')),
                ('recipes_price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('recipes_register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ذخیره سازی')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('recipes_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food', verbose_name='غذا')),
                ('recipes_stuffs', models.ManyToManyField(to='food.stuff', verbose_name='مواد استفاده شده')),
                ('recipes_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستور پخت من',
                'verbose_name_plural': 'دستورات پخت من',
                'db_table': 'table_food_my_recipes',
            },
        ),
        migrations.CreateModel(
            name='FoodStuffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('stuffs', models.ManyToManyField(to='food.stuff', verbose_name='ماده')),
            ],
            options={
                'verbose_name': 'نوع ماده',
                'verbose_name_plural': 'نوع مواد',
                'db_table': 'table_food_stuff_type',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='food_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodgroup', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_meal',
            field=models.ManyToManyField(to='food.meal', verbose_name='وعده\u200cی غذایی'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recipes', verbose_name='دستور پخت'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_stuff_types',
            field=models.ManyToManyField(blank=True, to='food.foodstufftype', verbose_name='گروه مواد استفاده شده'),
        ),
    ]
