# File version
__version__ = "1.1.1"
# File Description
"""
Django settings for food project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from os.path import join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%d2cq6nt0b)vr5m%ejhmae@772q-4s@x4l8@4m-e=bc+cf=&t1'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# handler404 = 'apps.main.views.http_status_404'

SITE_ID = 2


# Application definition
from django.apps import registry
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.utils.translation',
    'apps.main.apps.MainConfig',
    'apps.blog.apps.BlogConfig',
    'apps.food.apps.FoodConfig', 
    'apps.message.apps.MessageConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.search.apps.SearchConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.discounts.apps.DiscountsConfig',
    'apps.payments.apps.PaymentsConfig',
    'apps.what_cook.apps.WhatCookConfig',
    'apps.comments.apps.CommentsConfig',
    'apps.scores.apps.ScoresConfig',
    'apps.favorites.apps.FavoritesConfig',
    'apps.branch.apps.BranchConfig',
    'apps.reservation.apps.ReservationConfig',
    'apps.data_manager.apps.DataManagerConfig',
    'apps.event.apps.EventConfig',
    'apps.language.apps.LanguageConfig',
    'apps.ad.apps.AdConfig',
    'apps.mukbang.apps.MukbangConfig',
    'apps.chat_gpt.apps.ChatGptConfig',
    'apps.gift.apps.GiftConfig',
    'apps.Email.apps.EmailConfig',    
    'apps.subscription.apps.SubscriptionConfig',    
    'apps.my_environment.apps.MyEnvironmentConfig',    
    'apps.delivery.apps.DeliveryConfig',    
    'django_render_partial',
    'colorfield',
    'ckeditor',
    'ckeditor_uploader',
    'rosetta',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google'
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE":[
            "profile",
            "email"
        ],
        "AUTH_PARAMS":{"access_type":"online"}
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Middleware.middleware.RequestMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]
SANDBOX=True
ROOT_URLCONF = 'food.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.data_manager.views.update_data',
                'apps.main.views.template_data',
                'apps.main.views.objects',
                'apps.language.views.get_language_code',
                # 'apps.accounts.views.user_info',
                # 'adminlte_full.context_processors.adminlte',
            ],
        },
    },
]

WSGI_APPLICATION = 'food.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'db_foodino',
        'USER': 'root',
        'PASSWORD': 'Soren',
        'HOST':'localhost',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


LOCALE_PATHS = [
    BASE_DIR / 'locale/',
]

from django.utils.translation import gettext_lazy as _
from json import load
LANGUAGE_CODE = 'fa'


LANGUAGES = [
    ('aa', _('Afar')),
    ('ab', _('Abkhazian')),
    ('af', _('Afrikaans')),
    ('ab', _('Abkhazian')),
    ('ab', _('Abkhazian')),
    ('aa', 'Afar'), 
    ('ab', 'Abkhazian'), 
    ('af', 'Afrikaans'), 
    ('ak', 'Akan'), 
    ('als', 'Alemannic'), 
    ('am', 'Amharic'), 
    ('an', 'Aragonese'), 
    ('ang', 'Anglo-Saxon\xa0/ Old English'), 
    ('ar', 'Arabic'), 
    ('arc', 'Aramaic'), 
    ('arz', 'Egyptian Arabic'), 
    ('as', 'Assamese'), 
    ('ast', 'Asturian'), 
    ('av', 'Avar'), 
    ('awa', 'Awadhi'), 
    ('ay', 'Aymara'), 
    ('az', 'Azerbaijani'), 
    ('ba', 'Bashkir'), 
    ('bar', 'Bavarian'), 
    ('bat-smg', 'Samogitian'), 
    ('bcl', 'Bikol'), 
    ('be', 'Belarusian'), 
    ('be-x-old', 'Belarusian (Taraškievica)'), 
    ('bg', 'Bulgarian'), 
    ('bh', 'Bihari'), 
    ('bi', 'Bislama'), 
    ('bm', 'Bambara'), 
    ('bn', 'Bengali'), 
    ('bo', 'Tibetan'), 
    ('bpy', 'Bishnupriya Manipuri'), 
    ('br', 'Breton'), 
    ('brx', 'Boro'), 
    ('bs', 'Bosnian'), 
    ('bug', 'Buginese'), 
    ('bxr', 'Buriat (Russia)'), 
    ('ca', 'Catalan'), 
    ('cdo', 'Min Dong Chinese'), 
    ('ce', 'Chechen'), 
    ('ceb', 'Cebuano'), 
    ('ch', 'Chamorro'), 
    ('cho', 'Choctaw'), 
    ('chr', 'Cherokee'), 
    ('chy', 'Cheyenne'), 
    ('ckb', 'Kurdish (Sorani)'), 
    ('co', 'Corsican'), 
    ('cr', 'Cree'), 
    ('crn', 'Montenegrin'), 
    ('cs', 'Czech'), 
    ('csb', 'Kashubian'), 
    ('cu', 'Old Church Slavonic\xa0/ Old Bulgarian'), 
    ('cv', 'Chuvash'), 
    ('cy', 'Welsh'), 
    ('da', 'Danish'), 
    ('de', 'German'), 
    ('diq', 'Dimli'), 
    ('dsb', 'Lower Sorbian'),
    ('dv', 'Divehi'), 
    ('dz', 'Dzongkha'), 
    ('ee', 'Ewe'), 
    ('el', 'Greek'), 
    ('en', 'English'), 
    ('eo', 'Esperanto'),
    ('es', 'Spanish'),
    ('et', 'Estonian'),
    ('eu', 'Basque'), 
    ('ext', 'Extremaduran'), 
    ('fa', 'Persian'), 
    ('ff', 'Peul'), 
    ('fi', 'Finnish'), 
    ('fiu-vro', 'Võro'), 
    ('fj', 'Fijian'), 
    ('fo', 'Faroese'), 
    ('fr', 'French'), 
    ('frp', 'Arpitan\xa0/ Franco-Provençal'), 
    ('fur', 'Friulian'), 
    ('fy', 'West Frisian'), 
    ('ga', 'Irish'), 
    ('gan', 'Gan Chinese'), 
    ('gbm', 'Garhwali'),
    ('gd', 'Scottish Gaelic'),
    ('gil', 'Gilbertese'),
    ('gl', 'Galician'), 
    ('gn', 'Guarani'), 
    ('got', 'Gothic'), 
    ('gu', 'Gujarati'), 
    ('gv', 'Manx'),
    ('ha', 'Hausa'),
    ('hak', 'Hakka Chinese'),
    ('haw', 'Hawaiian'), 
    ('he', 'Hebrew'), 
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'), 
    ('hr', 'Croatian'), 
    ('ht', 'Haitian'), 
    ('hu', 'Hungarian'), 
    ('hy', 'Armenian'), 
    ('hz', 'Herero'), 
    ('ia', 'Interlingua'),
    ('id', 'Indonesian'),
    ('ie', 'Interlingue'),
    ('ig', 'Igbo'),
    ('ii', 'Sichuan Yi'),
    ('ik', 'Inupiak'),
    ('ilo', 'Ilokano'), 
    ('inh', 'Ingush'), 
    ('io', 'Ido'), 
    ('is', 'Icelandic'), 
    ('it', 'Italian'), 
    ('iu', 'Inuktitut'), 
    ('ja', 'Japanese'), 
    ('jbo', 'Lojban'), 
    ('jv', 'Javanese'), 
    ('ka', 'Georgian'), 
    ('kg', 'Kongo'), 
    ('ki', 'Kikuyu'), 
    ('kj', 'Kuanyama'), 
    ('kk', 'Kazakh'), 
    ('kl', 'Greenlandic'), 
    ('km', 'Cambodian'), 
    ('kn', 'Kannada'), 
    ('khw', 'Khowar'), 
    ('ko', 'Korean'), 
    ('kr', 'Kanuri'), 
    ('ks', 'Kashmiri'), 
    ('ksh', 'Ripuarian'), 
    ('ku', 'Kurdish (Kurmanji)'), 
    ('kv', 'Komi'), 
    ('kw', 'Cornish'), 
    ('ky', 'Kirghiz'), 
    ('la', 'Latin'), 
    ('lad', 'Ladino\xa0/ Judeo-Spanish'), 
    ('lan', 'Lango'), 
    ('lb', 'Luxembourgish'), 
    ('lg', 'Ganda'), 
    ('li', 'Limburgian'), 
    ('lij', 'Ligurian'),
    ('lmo', 'Lombard'), 
    ('ln', 'Lingala'), 
    ('lo', 'Laotian'), 
    ('lzz', 'Laz'), 
    ('lt', 'Lithuanian'),
    ('lv', 'Latvian'),
    ('map-bms', 'Banyumasan'),
    ('mg', 'Malagasy'), 
    ('man', 'Mandarin'), 
    ('mh', 'Marshallese'),
    ('mi', 'Māori'),
    ('min', 'Minangkabau'),
    ('mk', 'Macedonian'), 
    ('ml', 'Malayalam'), 
    ('mn', 'Mongolian'),
    ('mo', 'Moldovan'), 
    ('mr', 'Marathi'), 
    ('mrh', 'Mara'), 
    ('ms', 'Malay'), 
    ('mt', 'Maltese'), 
    ('mus', 'Creek\xa0/ Muskogee'), 
    ('mwl', 'Mirandese'), 
    ('my', 'Burmese'), 
    ('na', 'Nauruan'), 
    ('nah', 'Nahuatl'), 
    ('nap', 'Neapolitan'),
    ('nd', 'North Ndebele'), 
    ('nds', 'Low German\xa0/ Low Saxon'), 
    ('nds-nl', 'Dutch Low Saxon'), 
    ('ne', 'Nepali'),
    ('new', 'Newar'), 
    ('ng', 'Ndonga'), 
    ('nl', 'Dutch'), 
    ('nn', 'Norwegian Nynorsk'), 
    ('no', 'Norwegian'), 
    ('nr', 'South Ndebele'), 
    ('nso', 'Northern Sotho'), 
    ('nrm', 'Norman'), 
    ('nv', 'Navajo'), 
    ('ny', 'Chichewa'), 
    ('oc', 'Occitan'), 
    ('oj', 'Ojibwa'), 
    ('om', 'Oromo'), 
    ('or', 'Oriya'), 
    ('os', 'Ossetian\xa0/ Ossetic'), 
    ('pa', 'Panjabi\xa0/ Punjabi'),
    ('pag', 'Pangasinan'), 
    ('pam', 'Kapampangan'), 
    ('pap', 'Papiamentu'), 
    ('pdc', 'Pennsylvania German'), 
    ('pi', 'Pali'), 
    ('pih', 'Norfolk'),
    ('pl', 'Polish'),
    ('pms', 'Piedmontese'), 
    ('ps', 'Pashto'), 
    ('pt', 'Portuguese'), 
    ('qu', 'Quechua'),
    ('rm', 'Raeto Romance'), 
    ('rmy', 'Romani'),
    ('rn', 'Kirundi'), 
    ('ro', 'Romanian'), 
    ('roa-rup', 'Aromanian'), 
    ('ru', 'Russian'), 
    ('rw', 'Rwandi'), 
    ('sa', 'Sanskrit'), 
    ('sc', 'Sardinian'), 
    ('scn', 'Sicilian'), 
    ('sco', 'Scots'), 
    ('sd', 'Sindhi'), 
    ('se', 'Northern Sami'), 
    ('sg', 'Sango'), 
    ('sh', 'Serbo-Croatian'), 
    ('si', 'Sinhalese'), 
    ('simple', 'Simple English'), 
    ('sk', 'Slovak'), 
    ('sl', 'Slovenian'), 
    ('sm', 'Samoan'), 
    ('sn', 'Shona'), 
    ('so', 'Somalia'), 
    ('sq', 'Albanian'),
    ('sr', 'Serbian'), 
    ('ss', 'Swati'), 
    ('st', 'Southern Sotho'),
    ('su', 'Sundanese'), 
    ('sv', 'Swedish'), 
    ('sw', 'Swahili'), 
    ('ta', 'Tamil'), 
    ('te', 'Telugu'), 
    ('tet', 'Tetum'),
    ('tg', 'Tajik'), 
    ('th', 'Thai'), 
    ('ti', 'Tigrinya'), 
    ('tk', 'Turkmen'),
    ('tl', 'Tagalog'), 
    ('tlh', 'Klingon'), 
    ('tn', 'Tswana'), 
    ('to', 'Tonga'), 
    ('tpi', 'Tok Pisin'),
    ('tr', 'Turkish'), 
    ('ts', 'Tsonga'), 
    ('tt', 'Tatar'), 
    ('tum', 'Tumbuka'), 
    ('tw', 'Twi'), 
    ('ty', 'Tahitian'), 
    ('udm', 'Udmurt'), 
    ('ug', 'Uyghur'), 
    ('uk', 'Ukrainian'), 
    ('ur', 'Urdu'), 
    ('uz', 'Uzbek'), 
    ('uz-af', 'Uzbeki Afghanistan'), 
    ('ve', 'Venda'), 
    ('vi', 'Vietnamese'), 
    ('vec', 'Venetian'), 
    ('vls', 'West Flemish'), 
    ('vo', 'Volapük'), 
    ('wa', 'Walloon'), 
    ('war', 'Waray\xa0/ Samar-Leyte Visayan'), 
    ('wo', 'Wolof'),
    ('xal', 'Kalmyk'),
    ('xh', 'Xhosa'),
    ('xmf', 'Megrelian'),
    ('yi', 'Yiddish'), ('yo', 'Yoruba'), ('za', 'Zhuang'), ('zg', 'Moroccan Amazigh'), ('zh', 'Chinese'), 
    ('zh-min-nan', 'Minnan'), 
    ('zh-yue', 'Cantonese'),
    ('zu', 'Zulu'), 
    ('closed-zh-tw', 'Traditional Chinese'), 
    ('nb', 'Norwegian Bokmål'),
    ('zh-tw', 'Traditional Chinese'), 
    ('tokipona', 'tokipona'),
]

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (join(BASE_DIR, 'static/'),)
MEDIA_URL = '/media/'
MEDIA_ROOT = join(BASE_DIR, 'media/')
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

URL = "http://127.0.0.1:8000/"
EMAIL = "info@sorenshamlou.ir"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'

CKEDITOR_UPLOAD_PATH = "images/ckeditor/upload_files/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
CKEDITOR_CONFIGS = {
    'default':
        {
            'toolbar':'Custom',
            'toolbar_Custom':[
                ['Bold','Link','Unlink','Image'],
            ]
        },
    'special':
        {
            'toolbar': 'Special', 'height':500,
            'toolbar': 'full',
            'toolbar_Special':
                [
                    ['Bold','Link','Unlink','Image'],
                    ['CodeSnippet'],
                ],'extraPlugins': ','.join(['codesnippet', 'clipboard'])
        },
    'special_an':
        {
            'toolbar': 'Special', 'height':500,
            'toolbar_Special':
                [
                    ['Bold'],
                    ['CodeSnippet'],
                ],'extraPlugins': ','.join(['codesnippet'])
            
        },
}


CRISPY_TEMPLATE_PACK = 'bootstrap4'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# ACCOUNT_EMAIL_REQUIRED = False
# ACCOUNT_PHONE_NUMBER_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
# ACCOUNT_AUTHENTICATION_METHOD = 'email'