# Generated by Django 4.0.5 on 2023-08-03 21:40

import apps.delivery.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_orderdetails_register_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=120, verbose_name='نام وسیله نقلیه')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'نوع وشیله نقلیه',
                'verbose_name_plural': 'انواع وسیله نقلیه',
                'db_table': 'table_vehicle_type',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=10, verbose_name='پلاک')),
                ('chassis_number', models.CharField(max_length=32, verbose_name='شماره شاسی')),
                ('profile_form', models.FileField(help_text='لطفا فایل فرم مشخصات خود را بارگذاری کنید. نکته: فرمت فایل باید pdf  باشد.', upload_to='files/delivery/profile_form', validators=[apps.delivery.models.validate_profile_form], verbose_name='فایل فرم مشخصات')),
                ('ID_card_image', models.ImageField(upload_to='images/delivery/ID_card_image', verbose_name='تصویر کارت شناسایی')),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ درج')),
                ('is_sending_the_order', models.BooleanField(default=False, verbose_name='درحال ارسال سفارش است؟')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
                ('VehicleType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.vehicletype', verbose_name='وسیله نقلیه')),
                ('the_orders_he_ro_she_has_won', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارشاتی که این پیک برده است')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیک',
                'verbose_name_plural': 'پیک\u200cها',
                'db_table': 'table_delivery',
            },
        ),
    ]
