# Generated by Django 4.0.5 on 2023-08-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='VehicleType',
            new_name='vehicle_type',
        ),
    ]
