# Generated by Django 4.0.5 on 2023-08-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdetails_register_date_time_and_more'),
        ('delivery', '0002_rename_vehicletype_delivery_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='the_orders_he_ro_she_has_won',
        ),
        migrations.AddField(
            model_name='delivery',
            name='the_orders_he_ro_she_has_won',
            field=models.ManyToManyField(to='orders.order', verbose_name='سفارشاتی که این پیک برده است'),
        ),
    ]
