# Generated by Django 4.0.5 on 2023-08-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='the_orders_he_ro_she_has_won',
        ),
    ]
