# Generated by Django 4.0.5 on 2023-08-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('delivery', '0005_remove_delivery_the_orders_he_ro_she_has_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branch.branch', verbose_name='شعبه\u200cای که در آن فعالیت میکنند'),
        ),
    ]
