# Generated by Django 4.0.5 on 2023-07-30 01:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=10, unique=True, verbose_name='کد کوپن')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('allowed_number_used', models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد مجاز استفاده شده')),
                ('number_used', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'بن تخفیف',
                'verbose_name_plural': 'بن تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=100, verbose_name='عنوان سبد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال/غیرفعال')),
                ('is_translated_content', models.BooleanField(default=False, verbose_name='آیا محتوا ترجمه شده؟')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_detail_1', to='discounts.discountbasket', verbose_name='سبد تخفیف')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_discount_basket_detail_2', to='food.food', verbose_name='غذا')),
                ('my_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_recipe_discount_basket_detail_2', to='food.myrecipes', verbose_name='غذای کاربر')),
            ],
            options={
                'verbose_name': 'جزء سبد تخفیف',
                'verbose_name_plural': 'جزئیات سبد تخفیف',
            },
        ),
    ]
